[package]
authors = ["Dan Whitman <dwhitman44@gmail.com>"]
categories = ["embedded", "hardware-support"]
description = "Board support crate for the Watchy programmable smart watch"
# This may need to be a custom URL at some point for self-hosted documentation
#documentation = ""
edition = "2021"
keywords = ["esp-idf", "esp32"]
license = "MIT"
name = "watchy"
readme = "README.md"
repository = "https://github.com/kyp44/watchy"
version = "0.1.0"

[features]
alloc = ["esp-idf-svc/alloc", "gdeh0154d67/heap_buffer"]
async-display = ["dep:embedded-hal-async", "gdeh0154d67/async"]
default = ["alloc", "std"]
embassy = [
  "esp-idf-svc/embassy-sync",
  "esp-idf-svc/critical-section",
  "esp-idf-svc/embassy-time-driver",
]
nightly = ["esp-idf-svc/nightly"]
std = ["alloc", "gdeh0154d67/std", "esp-idf-svc/std"]

[dependencies]
bma423 = "0.0.4"
embedded-hal = "1.0.0"
embedded-hal-async = {version = "1.0.0", optional = true}
enumset = "1.1.14"
esp-idf-hal = {version = "0.46.2", default-features = false, features = ["timer-legacy"]}
esp-idf-svc = {version = "0.52.1", default-features = false}
gdeh0154d67 = {version = "0.3.0", default-features = false}
log = {version = "0.4.28", default-features = false}
rounded-div = "0.1.4"
thiserror = "2.0.20"
